### ISSUE TITLE
Ability to maximize videos

### ISSUE THREAD

**Issue by jahd2602** [indywidualny/FaceSlim#24]
It's possible to play videos posted in the social network but it's not possible to maximize them using the button from the lower-right corner. It is possible via Chrome entering m.facebook.com though.

**Comment by G33KS44n** [comment]
@jahd2602  lemme check it and i will get back to you

**Comment by indywidualny** [comment]
All the videos are opened in the external browser (or YouTube) at my device so I cannot test it.

**Comment by pejakm** [comment]
I'm having this problem as well. It can be really annoying.

**Comment by indywidualny** [comment]
Give me an example url. It have to be public. I have no idea where to test it.

**Comment by pejakm** [comment]
Here it is, the first I came across:
https://www.facebook.com/story.php?story_fbid=911484298928200&id=218558234887480

On my mobile browser (Lightning Browser) I can play it fullscreen, but there's no such option in Face Slim.

**Comment by indywidualny** [comment]
Well. At my device the player doesn't even have an option to make it full screen. There are just play, time indicator and sound volume ;(

**Comment by indywidualny** [comment]
But it's curious. I will look for an answer.

**Comment by indywidualny** [comment]
Perhaps I found a solution. It's gonna be tested soon. Give me a few days. Busy time now.

**Comment by indywidualny** [comment]
Just a note to myself: http://stackoverflow.com/questions/15796661/android-webview-app-wont-let-video-player-go-full-screen/16199649#16199649

**Comment by juzman** [comment]
I have the same issue. They play small, and only have play/time/indicator/volume. No option to full screen.

**Comment by indywidualny** [comment]
Sure you have. Not resolved yet ;)

sob., 9.01.2016, 06:05 Justyn Smith użytkownik <notifications@github.com>
napisał:

**Comment by pejakm** [comment]
After latest changes there is a button to maximize the video, but FaceSlim crashes if I open the video in full screen.

**Comment by indywidualny** [comment]
Please send an error report. You should get an error reporting dialog
during a crash.

pt., 15.01.2016, 11:59 Mladen Pejaković użytkownik <notifications@github.com>
napisał:

**Comment by pejakm** [comment]
> Please send an error report. You should get an error reporting dialog
during a crash.

Forgot to mention, there was no error reporting dialog at all.

**Comment by indywidualny** [comment]
Shit. It there any stacktrace in your logs? You have to copy it quickly during the force close. It has to be something more.

**Comment by pejakm** [comment]
Okay, I didn't filter logcat output this, hopefully it has more data now:

```
I/ActivityManager(28457): Displayed org.indywidualni.fblite/.activity.SplashActivity: +507ms
I/Timeline(28457): Timeline: Activity_windows_visible id: ActivityRecord{13046187 u0 org.indywidualni.fblite/.activity.SplashActivity t64} time:8458740
I/Timeline( 9535): Timeline: Activity_launch_request id:org.indywidualni.fblite time:8458812
I/ActivityManager(28457): START u0 {cmp=org.indywidualni.fblite/.activity.MainActivity} from uid 10174 on display 0
V/WindowManager(28457): addAppToken: AppWindowToken{19329c4e token=Token{1b48eb49 ActivityRecord{15f97d50 u0 org.indywidualni.fblite/.activity.MainActivity t64}}} to stack=1 task=64 at 1
V/WindowManager(28457): rotationForOrientationLw(orient=-1, last=0); user=0
I/WebViewFactory( 9535): Loading com.android.webview version 39 (eng.alf-arm) (code 399991)
I/LibraryLoader( 9535): Time to load native libraries: 3 ms (timestamps 9236-9239)
I/LibraryLoader( 9535): Expected native library version number "",actual native library version number ""
V/WebViewChromiumFactoryProvider( 9535): Binding Chromium to main looper Looper (main, tid 1) {2b5243ff}
I/LibraryLoader( 9535): Expected native library version number "",actual native library version number ""
I/chromium( 9535): [INFO:library_loader_hooks.cc(104)] Chromium logging enabled: level = 0, default verbosity = 0
I/BrowserStartupController( 9535): Initializing chromium process, singleProcess=true
W/art     ( 9535): Attempt to remove local handle scope entry from IRT, ignoring
W/AudioManagerAndroid( 9535): Requires BLUETOOTH permission
W/chromium( 9535): [WARNING:resource_bundle.cc(304)] locale_file_path.empty()
I/chromium( 9535): [INFO:aw_browser_main_parts.cc(65)] Load from apk succesful, fd=45 off=181692 len=5176
I/chromium( 9535): [INFO:aw_browser_main_parts.cc(78)] Loading webviewchromium.pak from, fd:46 off:229484 len:1089587
W/chromium( 9535): [WARNING:data_reduction_proxy_settings.cc(331)] SPDY proxy OFF at startup
W/art     ( 9535): Attempt to remove local handle scope entry from IRT, ignoring
W/AwContents( 9535): onDetachedFromWindow called when already detached. Ignoring
V/WindowManager(28457): Adding window Window{364a7dbd u0 org.indywidualni.fblite/org.indywidualni.fblite.activity.MainActivity} at 7 of 11 (after Window{3ce2ba77 u0 org.indywidualni.fblite/org.indywidualni.fblite.activity.SplashActivity})
I/ActivityManager(28457): Displayed org.indywidualni.fblite/.activity.MainActivity: +747ms
I/Timeline( 9535): Timeline: Activity_idle id: android.os.BinderProxy@2f46b6a6 time:8459605
I/Timeline(28457): Timeline: Activity_windows_visible id: ActivityRecord{15f97d50 u0 org.indywidualni.fblite/.activity.MainActivity t64} time:8459801
V/nvaudio_hw(28358): nvaudio_out_standby
V/nvaudio_hw(28358): close_alsa_dev : active stream count 1
D/TaskPersister(28457): removeObsoleteFile: deleting file=62_task.xml
D/TaskPersister(28457): removeObsoleteFile: deleting file=62_task_thumbnail.png
D/MediaResourceGetter( 9535): ethernet/wifi connection detected
I/StagefrightMetadataRetriever(28358): setDataSource(https://<suppressed>)
D/MediaHTTPConnection( 9535): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection( 9535): proxy null port 0
I/NuCachedSource2(28358): caching reached eos.
D/MediaResourceGetter( 9535): resource has video
D/MediaResourceGetter( 9535): extracted valid metadata: MediaMetadata[durationInMilliseconds=16167, width=400, height=400, success=true]
E/ExtMediaPlayer-JNI( 9535): QCMediaPlayer could not be located....
E/MediaPlayer-JNI( 9535): QCMediaPlayer mediaplayer NOT present
I/MediaFocusControl(28457):  AudioFocus  requestAudioFocus() from android.media.AudioManager@2ef141dcom.android.org.chromium.media.MediaPlayerListener@35a9692 req=3flags=0x0
D/MediaPlayer( 9535): Couldn't open file on client side, trying server side
D/MediaHTTPConnection( 9535): filterOutInternalHeaders: key=User-Agent, val= stagefright/1.2 (Linux;Android 5.1.1)
D/MediaHTTPConnection( 9535): filterOutInternalHeaders: key=allow-cross-domain-redirect, val= false
D/MediaHTTPConnection( 9535): proxy null port 0
I/NuCachedSource2(28358): caching reached eos.
E/MediaPlayer( 9535): Should have subtitle controller already set
D/NuPlayerDriver(28358): start(0xb5873a00)
I/GenericSource(28358): start
D/MediaPlayer( 9535): getMetadata
W/Utils   (28358): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
I/NuPlayer(28358): Could not offload audio decode, pcm offload decided :0
W/Utils   (28358): bool android::canOffloadStream(const android::sp<android::MetaData>&, bool, const android::sp<android::MetaData>&, bool, audio_stream_type_t) No sample bit depth info in meta data
D/NvOsDebugPrintf(28358): NvxLiteH264DecoderInit : Opening TVMR H264 block
I/ACodec  (28358): sampleRate=22050 channels=1 bits=16
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
E/OMXNodeInstance(28358): setParameter(b6:Nvidia.h264.decode, OMX.google.android.index.storeMetaDataInBuffers(0x7fc00007): Output:1 en=1 GB=0) ERROR: NotImplemented(0x80001006)
E/ACodec  (28358): [OMX.Nvidia.h264.decode] storeMetaDataInBuffers failed w/ err -2147483648
I/ACodec  (28358): [OMX.Nvidia.h264.decode] DRC Mode: Port Reconfig Mode
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
I/SoftAAC2(28358): limiting to stereo output
I/SoftAAC2(28358): Reconfiguring decoder: 0->44100 Hz, 0->2 channels
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
E/AudioTrack(28358): AudioTrack::set : Exit
V/nvaudio_hw(28358): nvaudio_dev_set_parameters : nv_param_media_routing=2
V/nvaudio_hw(28358): Media is routed to :2
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): NvMMLiteOpen : Block : BlockType = 261
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecBlockOpen: 2867: NvMMLiteBlockOpen
D/NvOsDebugPrintf(28358): TVMR: TVMRFrameDelivery: 2048: TVMRFrameDelivery Started
D/NvOsDebugPrintf(28358): NvMMLiteBlockCreate : Block : BlockType = 261
D/NvOsDebugPrintf(28358): TVMR: cbBeginSequence: 234: BeginSequence 400x400
D/NvOsDebugPrintf(28358): TVMR: cbBeginSequence: 421: pnvsi->nDecodeBuffers = 6
D/NvOsDebugPrintf(28358): TVMR: cbBeginSequence: 431: Display Resolution : (400x400)
D/NvOsDebugPrintf(28358): TVMR: cbBeginSequence: 432: Display Aspect Ratio : (400x400)
D/NvOsDebugPrintf(28358): TVMR: cbBeginSequence: 504: SurfaceLayout = 2
D/NvOsDebugPrintf(28358): TVMR: cbBeginSequence: 519: NumOfSurfaces = 10, InteraceStream = 0, InterlaceEnabled = 0
D/NvOsDebugPrintf(28358): Allocating new output: 400x400 (x 12)
D/NvOsDebugPrintf(28358): OMX minor version mismatch
E/OMXNodeInstance(28358): setParameter(b6:Nvidia.h264.decode, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
W/ACodec  (28358): [OMX.Nvidia.h264.decode] setting nBufferCountActual to 17 failed: -1010
E/OMXNodeInstance(28358): setParameter(b6:Nvidia.h264.decode, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
W/ACodec  (28358): [OMX.Nvidia.h264.decode] setting nBufferCountActual to 16 failed: -1010
E/OMXNodeInstance(28358): setParameter(b6:Nvidia.h264.decode, ParamPortDefinition(0x2000001)) ERROR: UnsupportedSetting(0x80001019)
W/ACodec  (28358): [OMX.Nvidia.h264.decode] setting nBufferCountActual to 15 failed: -1010
V/nvaudio_hw(28358): open_out_alsa_dev dev->id 0, out->format 1 is_pass_thru 0
V/nvaudio_hw(28358): set_out_resampler : quality 4 out->rate 48000, dev->config.rate 48000,
V/nvaudio_hw(28358): set_out_resampler : quality 4 out->channel_count 2, dev->config.channels 2,
V/nvaudio_hw(28358): No resampler required
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
D/NvOsDebugPrintf(28358): OMX minor version mismatch
W/MediaPlayer( 9535): info/warning (3, 0)
W/System.err( 9535): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setVisibility(int)' on a null object reference
W/System.err( 9535):    at org.indywidualni.fblite.activity.g.onShowCustomView(Unknown Source)
W/System.err( 9535):    at com.android.webview.chromium.WebViewContentsClientAdapter.onShowCustomView(WebViewContentsClientAdapter.java:962)
W/System.err( 9535):    at com.android.org.chromium.android_webview.AwContentViewClient$AwContentVideoViewClient.onShowCustomView(AwContentViewClient.java:66)
W/System.err( 9535):    at com.android.org.chromium.content.browser.ContentVideoView.createContentVideoView(ContentVideoView.java:429)
W/System.err( 9535):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 9535):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err( 9535):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 9535):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 9535):    at android.app.ActivityThread.main(ActivityThread.java:5294)
W/System.err( 9535):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9535):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 9535):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
W/System.err( 9535):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
F/chromium( 9535): [FATAL:jni_android.cc(269)] Check failed: false. Please include Java exception stack in crash report
F/libc    ( 9535): Fatal signal 6 (SIGABRT), code -6 in tid 9535 (widualni.fblite)
I/libc    ( 9535): Suppressing debuggerd output because prctl(PR_GET_DUMPABLE)==0
E/Surface (28358): queueBuffer: error queuing buffer to SurfaceTexture, -32
E/ACodec  (28358): signalError(omxError 0x80001001, internalError -2147483648)
I/WindowState(28457): WIN DEATH: Window{364a7dbd u0 org.indywidualni.fblite/org.indywidualni.fblite.activity.MainActivity}
W/MediaFocusControl(28457):   AudioFocus   audio focus client died
I/MediaFocusControl(28457): AudioFocus  removeFocusStackEntry(): removing entry for android.os.BinderProxy@2c071eac
E/MediaCodec(28358): Codec reported err 0x80001001, actionCode 0, while in state 6
W/MediaCodec(28358): native_window_api_disconnect returned an error: Broken pipe (-32)
D/NuPlayerDriver(28358): reset(0xb5873a00)
E/NuPlayerDecoder(28358): Failed to dequeue output buffer for OMX.Nvidia.h264.decode (err=-38)
E/NuPlayer(28358): received error(0xffffffda) from video decoder, flushing(2), now shutting down
E/NuPlayerDecoder(28358): failed to flush OMX.Nvidia.h264.decode (err=-38)
E/NuPlayer(28358): received error(0xffffffda) from video decoder, flushing(2), now shutting down
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecAbortBuffers: 2965: StreamIndex = 0
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecAbortBuffers: 3230: StreamIndex = 0, AbortStatus = 1, Done
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecAbortBuffers: 2965: StreamIndex = 1
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecAbortBuffers: 3230: StreamIndex = 1, AbortStatus = 3, Done
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecAbortBuffers: 2965: StreamIndex = 0
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecAbortBuffers: 3230: StreamIndex = 0, AbortStatus = 1, Done
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecAbortBuffers: 2965: StreamIndex = 1
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecAbortBuffers: 3230: StreamIndex = 1, AbortStatus = 3, Done
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5b00
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 33 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5a40
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 32 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5380
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 31 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5c80
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 30 to native window
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecBlockClose: 2929
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecPrivateClose: 2443 ++
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5200
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 29 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5bc0
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 28 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5080
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 27 to native window
D/NvOsDebugPrintf(28358): TVMR: TVMRFrameDelivery: 2055: Closing TVMR Frame Delivery Thread -------------
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d4fc0
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 26 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d52c0
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 24 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5440
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 23 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d55c0
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 21 to native window
E/Surface (28358): getSlotFromBufferLocked: unknown buffer: 0xa94d5680
W/ACodec  (28358): [OMX.Nvidia.h264.decode] can not return buffer 20 to native window
D/NvOsDebugPrintf(28358): TVMR: NvMMDecTVMRDestroyParser: 2421: NvAvpClose
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecPrivateClose: 2456: NvMMLiteTVMRDecPrivateClose Done
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecPrivateClose: 2458 --
D/NvOsDebugPrintf(28358): TVMR: NvMMLiteTVMRDecBlockClose: 2934: Done
W/NuPlayerDecoder(28358): [OMX.Nvidia.h264.decode] failed to connect to native window, error=-32
D/NuPlayerDriver(28358): notifyResetComplete(0xb5873a00)
W/MediaPlayerService(28358): native_window_api_disconnect returned an error: Broken pipe (-32)
W/AudioFlinger(28358): session id 44 not found for pid 9535
V/nvaudio_hw(28358): nvaudio_dev_set_parameters : nv_param_media_routing=2
V/nvaudio_hw(28358): Media is routed to :2
I/Zygote  (28350): Process 9535 exited due to signal (6)
I/ActivityManager(28457): Process org.indywidualni.fblite (pid 9535) has died
W/ActivityManager(28457): Force removing ActivityRecord{15f97d50 u0 org.indywidualni.fblite/.activity.MainActivity t64}: app died, no saved state
V/WindowManager(28457): rotationForOrientationLw(orient=5, last=0); user=0
W/InputMethodManagerService(28457): Got RemoteException sending setActive(false) notification to pid 9535 uid 10174
I/Timeline(29145): Timeline: Activity_idle id: android.os.BinderProxy@11edd519 time:8480349
I/Timeline(28457): Timeline: Activity_windows_visible id: ActivityRecord{397ebac7 u0 com.cyanogenmod.trebuchet/com.android.launcher3.Launcher t29} time:8480517
W/OpenGLRenderer(29145): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
W/OpenGLRenderer(29145): Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
V/nvaudio_hw(28358): nvaudio_out_standby
V/nvaudio_hw(28358): close_alsa_dev : active stream count 1
V/nvaudio_hw(28358): nvaudio_dev_set_parameters : nv_param_media_routing=2
V/nvaudio_hw(28358): Media is routed to :2
V/nvaudio_hw(28358): open_out_alsa_dev dev->id 0, out->format 1 is_pass_thru 0
V/nvaudio_hw(28358): set_out_resampler : quality 4 out->rate 48000, dev->config.rate 48000,
V/nvaudio_hw(28358): set_out_resampler : quality 4 out->channel_count 2, dev->config.channels 2,
V/nvaudio_hw(28358): No resampler required
V/nvaudio_hw(28358): nvaudio_dev_set_parameters : nv_param_media_routing=2
V/nvaudio_hw(28358): Media is routed to :2
W/OpenGLRenderer(29145): Incorrectly called buildLayer on View: OverviewPanel, destroying layer...
V/nvaudio_hw(28358): nvaudio_dev_get_parameters : fm_audio
I/str_params(28358): key: 'fm_audio' value: ''
V/nvaudio_hw(28358): nvaudio_dev_set_parameters : nv_param_media_routing=2
V/nvaudio_hw(28358): Media is routed to :2
I/Timeline(29145): Timeline: Activity_launch_request id:jackpal.androidterm time:8485433
I/ActivityManager(28457): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=jackpal.androidterm/.Term (has extras)} from uid 10017 on display 0
V/WindowManager(28457): addAppToken: AppWindowToken{2b1d7998 token=Token{3c8f277b ActivityRecord{2c13230a u0 jackpal.androidterm/.Term t65}}} to stack=1 task=65 at 0
V/WindowManager(28457): Adding window Window{69c229 u0 Starting jackpal.androidterm} at 6 of 10 (after Window{1f3f2d1d u0 com.amaze.filemanager/com.amaze.filemanager.activities.MainActivity})
I/ActivityManager(28457): Start proc 10705:jackpal.androidterm/u0a52 for activity jackpal.androidterm/.Term
V/WindowManager(28457): rotationForOrientationLw(orient=-1, last=0); user=0
V/nvaudio_hw(28358): nvaudio_dev_get_parameters : fm_audio
I/str_params(28358): key: 'fm_audio' value: ''
V/nvaudio_hw(28358): nvaudio_dev_set_parameters : nv_param_media_routing=2
V/nvaudio_hw(28358): Media is routed to :2
I/LoadedApk(10705): No resource references to update in package org.twelf.cmtheme
V/Term    (10705): onCreate
D/OpenGLRenderer(10705): Use EGL_SWAP_BEHAVIOR_PRESERVED: false
V/WindowManager(28457): Adding window Window{2a23f086 u0 jackpal.androidterm/jackpal.androidterm.Term} at 6 of 11 (before Window{69c229 u0 Starting jackpal.androidterm})
D/Term    (10705): TermService started
I/TermService(10705): Activity called onBind()
D/libEGL  (10705): loaded /system/lib/egl/libEGL_tegra.so
E/        (10705): file /data/data/com.nvidia.NvCPLSvc/files/driverlist.txt: not found!
I/        (10705): Attempting to load EGL implementation /system/lib//egl/libEGL_tegra_impl
I/        (10705): Loaded EGL implementation /system/lib//egl/libEGL_tegra_impl
D/libEGL  (10705): loaded /system/lib/egl/libGLESv1_CM_tegra.so
D/libEGL  (10705): loaded /system/lib/egl/libGLESv2_tegra.soI/OpenGLRenderer(10705): Initialized EGL, version 1.4
I/        (10705): Loading GLESv2 implementation /system/lib//egl/libGLESv2_tegra_impl
D/OpenGLRenderer(10705): Enabling debug mode 0
I/Term    (10705): Bound to TermService
I/TermService(10705): Activity binding to service
I/libjackpal-androidterm(10705): JNI_OnLoad
I/Term    (10705): waiting for: 10729
I/ActivityManager(28457): Displayed jackpal.androidterm/.Term: +978ms
I/Timeline(28457): Timeline: Activity_windows_visible id: ActivityRecord{2c13230a u0 jackpal.androidterm/.Term t65} time:8486493
I/Timeline(10705): Timeline: Activity_idle id: android.os.BinderProxy@205d43a5 time:8486502
W/ResourceType(32486): No package identifier when getting value for resource number 0x00000000
W/PackageManager(32486): Failure retrieving resources for org.indywidualni.fblite: Resource ID #0x0
W/OpenGLRenderer(32486): Incorrectly called buildLayer on View: TextView, destroying layer...
W/SubtypeLocaleUtils(29007): KeyboardLayoutSet not found, use QWERTY: locale=en_AU extraValue=TrySuppressingImeSwitcher,AsciiCapable,SupportTouchPositionCorrection,EmojiCapable
W/SubtypeSwitcher(29007): Can't find emoji subtype
W/SubtypeSwitcher(29007): No input method subtype found; returning dummy subtype: android.view.inputmethod.InputMethodSubtype@d78b2ed0
W/ViewPager(29007): Requested offscreen page limit 0 too small; defaulting to 1
I/LatinIME(29007): Starting input. Cursor position = -1,-1
E/RichInputConnection(29007): Unable to connect to the editor to retrieve text.
D/RichInputConnection(29007): Will try to retrieve text later.
I/InputAttributes(29007): InputType.TYPE_NULL is specified
V/nvaudio_hw(28358): nvaudio_out_standby
V/nvaudio_hw(28358): close_alsa_dev : active stream count 1
```

**Comment by pejakm** [comment]
I believe the most relevant part is:

```
W/System.err( 9535): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.FrameLayout.setVisibility(int)' on a null object reference
W/System.err( 9535):    at org.indywidualni.fblite.activity.g.onShowCustomView(Unknown Source)
W/System.err( 9535):    at com.android.webview.chromium.WebViewContentsClientAdapter.onShowCustomView(WebViewContentsClientAdapter.java:962)
W/System.err( 9535):    at com.android.org.chromium.android_webview.AwContentViewClient$AwContentVideoViewClient.onShowCustomView(AwContentViewClient.java:66)
W/System.err( 9535):    at com.android.org.chromium.content.browser.ContentVideoView.createContentVideoView(ContentVideoView.java:429)
W/System.err( 9535):    at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 9535):    at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
W/System.err( 9535):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 9535):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 9535):    at android.app.ActivityThread.main(ActivityThread.java:5294)
W/System.err( 9535):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 9535):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 9535):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
W/System.err( 9535):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
F/chromium( 9535): [FATAL:jni_android.cc(269)] Check failed: false. Please include Java exception stack in crash report
F/libc    ( 9535): Fatal signal 6 (SIGABRT), code -6 in tid 9535 (widualni.fblite)
```

**Comment by indywidualny** [comment]
Thanks. It's obvious now. NullPointerException. Is it ok now?

**Comment by pejakm** [comment]
Crashed again, same error.

**Comment by indywidualny** [comment]
Holy guacamole. Ok, will find the problem in the evening.

pt., 15.01.2016, 14:57 Mladen Pejaković użytkownik <notifications@github.com>
napisał:

**Comment by pejakm** [comment]
I've got it! If I place a menu to the right, it crashes! If the menu is set to be on the left side (which is default), then it does not crash!

**Comment by indywidualny** [comment]
Lol. I forgot to add this element to right layout xD

pt., 15.01.2016, 15:07 Mladen Pejaković użytkownik <notifications@github.com>
napisał:

**Comment by pejakm** [comment]
:D I added it now, compiling as we speak.
