### ISSUE TITLE
Notification cookie (null) 

### ISSUE THREAD

**Issue by Leny1996** [indywidualny/FaceSlim#293]
Hi, after last update notifications stopped working. Tried to clear app data and login again - still error. 

Code from log:
```
2017-09-25 10:28:25.624 CheckNotificationsTask: Trying: https://m.facebook.com/notifications.php
2017-09-25 10:28:25.645 CheckNotificationsTask: Cookie sync problem occurred
java.lang.IllegalArgumentException: Cookie value must not be null
	at org.a.a.d.a(Validate.java:26)
	at org.a.a.b$a.b(HttpConnection.java:353)
	at org.a.a.b.b(HttpConnection.java:197)
	at org.indywidualni.fblite.service.NotificationsService$b.a(NotificationsService.java:200)
	at org.indywidualni.fblite.service.NotificationsService$b.doInBackground(NotificationsService.java:2226)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by indywidualny** [comment]
Ok. Thanks. I will check it. For now you can use the previous version. The new one is mostly TOR support which i suppose you don't need anyway.

**Comment by Leny1996** [comment]
Yea, but both version have problem with notifications. In previous after clicking on notification it redirects to home page.

**Comment by indywidualny** [comment]
Should be better now. I've reverted the old, working code when not TOR. No time for a better fix.

**Comment by Leny1996** [comment]
No problem, thanks.
Could you release this? I don't have tools to compile it by myself.

**Comment by indywidualny** [comment]
Sure https://github.com/indywidualny/FaceSlim/commit/3807293ad30ead4666fe7660ca96c7b84b894dee

**Comment by indywidualny** [comment]
Just tell me is it better now. When all ok I will make it public.

**Comment by Leny1996** [comment]
Okay. For now no errors, but don't have any new notifications on fb. I will write here when get any notification.
